Ch3 fixes
ModDota/dota-tutorial pull request #259
Opened 2021-03-13 14:06 UTC by Wouterz90

#244

2021-03-13 14:06 UTC, RobinKa requested changes
Please use proper formatting, it's very hard to read and undoing it every time takes a lot of time. (especially for the function calls)

2021-03-13 15:44 UTC, Wouterz90 commented
I have no idea, just using the alt shift f command which seems to cut of lines very soon, opening another editor to format now

2021-03-13 16:35 UTC, RobinKa commented
Still a lot of changed stuff. Is it possible you start from how it was and only make the actual changes from there?

2021-03-13 17:13 UTC, Wouterz90 commented
I guess that's the best solution for now

2021-03-14 18:37 UTC, RobinKa commented
![image](https://user-images.githubusercontent.com/2614101/111079966-433eae00-84f4-11eb-96f4-2037e42c28f6.png)

I received 2 of each neutral item

2021-03-14 20:48 UTC, RobinKa commented
- When you fail to stack at the 0/5 part, ODPixel says his line twice
- Camp after the N/5 section doesn't respawn and goal immediately completes, getting the player stuck

![image](https://user-images.githubusercontent.com/2614101/111083680-a2a5b980-8506-11eb-872f-d981d402e405.png)

2021-03-14 21:21 UTC, Wouterz90 commented
Ill test this more thoroughly tomorrow

Should have solved your second point, my solution for the first wasn't right. I got an idea for that.

2021-03-15 20:21 UTC, Wouterz90 commented
Need to remove 1 more line

2021-03-15 21:06 UTC, RobinKa commented on game/scripts/vscripts/Sections/Chapter3/Chapter3.ts
> +                //playerHero.AddNewModifier(undefined, undefined, "modifier_keep_hero_alive", undefined);
Remove this?

2021-03-15 21:06 UTC, RobinKa commented on game/scripts/vscripts/Sections/Chapter3/Chapter3.ts
> +            tg.loop(_ => tryCount <= 5, _ => { // Set this back to 5 // Remove the hardcoding
Comment still accurate / remove it?

2021-03-15 21:20 UTC, RobinKa commented
- After skip neutral items stick around (need to remove those in setupState too)
- Item slot if hardcoded for neutrals
- OD should say his stack unsuccessful line instead of repeating the previous one on stack fail
- Sometimes creeps randomly respawn (from ingame time I assume) which is kinda confusing

![image](https://user-images.githubusercontent.com/2614101/111222658-0c3fc980-85d4-11eb-85de-4b9419231ed3.png)

2021-03-15 21:23 UTC, merged